### ISSUE TITLE
mtXcontrol does not seem to run on G4 macs

### ISSUE THREAD

**Issue by GorillaCoder** [rngtng/mtXcontrol#6]
I'm helping someone on an arduino project. Today he was telling me about another project he wants to explore: rainbowduino. He had downloaded mtXcontrol, but when launching it nothing much seemed to happen. His machine is a G4 based Mac. Seems that Java 1.6 does not run on G4 macs, and therefore he has Java 1.5 loaded. Was wondering whether there are any issues running mtXcontrol on G4 macs or Java 1.5.

Thanks

**Comment by rngtng** [comment]
closing issue. pls reopen if problem still exists
